### ISSUE TITLE
what is cwbvh

### ISSUE THREAD

**Issue by DeJhon-Huang** [Pjbomb2/TrueTrace-Unity-Pathtracer#22]

**Comment by Pjbomb2** [comment]
Hello! Sorry for the late reply.
A CWBVH is a compressed bounding volume hierarchy.  I use it because its the fastest BVH I know of without doing hardware RT(though I am always looking for faster)
It is by far the fastest in incoherent(non primary) rays
https://research.nvidia.com/sites/default/files/publications/ylitie2017hpg-paper.pdf

**Comment by DeJhon-Huang** [comment]
Thanks for your reply, it was very helpful!
